INSERT INTO regiones (id,sigla,detalle) values (1,'I','Región de Tarapacá');
INSERT INTO regiones (id,sigla,detalle) values (2,'II','Región de Antofagasta');
INSERT INTO regiones (id,sigla,detalle) values (3,'III','Región de Atacama');
INSERT INTO regiones (id,sigla,detalle) values (4,'IV','Región de Coquimbo');
INSERT INTO regiones (id,sigla,detalle) values (5,'V','Región de Valparaíso');
INSERT INTO regiones (id,sigla,detalle) values (6,'VI','Región del Libertador General Bernardo O’Higgins');
INSERT INTO regiones (id,sigla,detalle) values (7,'VII','Región del Maule');
INSERT INTO regiones (id,sigla,detalle) values (8,'VIII','Región del Biobío');
INSERT INTO regiones (id,sigla,detalle) values (9,'IX','Región de La Araucanía');
INSERT INTO regiones (id,sigla,detalle) values (10,'X','Región de Los Lagos');
INSERT INTO regiones (id,sigla,detalle) values (11,'XI','Región Aysén del General Carlos Ibáñez del Campo');
INSERT INTO regiones (id,sigla,detalle) values (12,'XII','Región de Magallanes y Antártica Chilena');
INSERT INTO regiones (id,sigla,detalle) values (13,'XIII','Región Metropolitana de Santiago');
INSERT INTO regiones (id,sigla,detalle) values (14,'XIV','Región de Los Ríos');
INSERT INTO regiones (id,sigla,detalle) values (15,'XV','Región de Arica y Parinacota');
INSERT INTO regiones (id,sigla,detalle) values (16,'XVI','Región de Ñuble');
INSERT INTO curso (id,nombre,imagen,fecinicio,fectermino,cupos,descripcion) VALUES (0,'Desarrollador FullStack Java','https://red.computerworld.es/archivos/202205/java-concurrency.png','2022-06-02','2022-11-02',30,'Desarrolla las habilidades necesarias para construir y mantener piezas de software en lenguaje Java . DURACIÓN: 480 HORAS');
INSERT INTO curso (id,nombre,imagen,fecinicio,fectermino,cupos,descripcion) VALUES (1,'Desarrollador FullStack Java','https://red.computerworld.es/archivos/202205/java-concurrency.png','2022-06-02','2022-11-02',30,'Desarrolla las habilidades necesarias para construir y mantener piezas de software en lenguaje Java . DURACIÓN: 480 HORAS');
INSERT INTO curso (id,nombre,imagen,fecinicio,fectermino,cupos,descripcion) VALUES (2,'Desarrollador Aplicaciones Front-End','https://www.cursosgis.com/wp-content/uploads/1-52.jpg','2022-06-02','2022-10-02', 20,'Desarrollo de habilidades para construir y mantener aplicaciones o sitios web, con HTML, CSS y JavaScript. Duración: 438 horas');
INSERT INTO curso (id,nombre,imagen,fecinicio,fectermino,cupos,descripcion) VALUES (3,'Desarrollador FullStack Python','https://i.blogs.es/1d8a5b/python1/450_1000.jpg','2022-06-02','2022-06-02',15,'Desarrollo de habilidades necesarias para construir, mantener y crear aplicaciones web en Python y operar una base de datos. DURACIÓN: 462 HORAS');
INSERT INTO estudiante (rut, password,enabled, nombre, telefono,direccion,email,id_region,id_curso,edad) values ('177263850','$2a$10$8.UnVuG9HHgffUDAlk8qfOuVGkqRzgVymGe07xd00DMxs.AQubh4a',1,'Sebastian', '98563248','Republica 252','estudiante@gmail.com',6,0,18);
INSERT INTO estudiante (rut, password,enabled, nombre, telefono,direccion,email,id_region,id_curso,edad) values ('admin','$2a$12$8H9QMAELtKyC1takEJY71ez6v2hrZtAKubV1a4HTg0uQBbJW2bejq',1,'administrador', '123456789','Calleadmin','admino@gmail.com',9,0,18);
INSERT INTO authorities (username, authority) values ('177263850','USER');
INSERT INTO authorities (username, authority) values ('admin','ADMIN');
